#!/usr/bin/env zsh

shell_debug_relay=$SHELL_DEBUG
# SHELL_DEBUG=true

# $SHELL_DEBUG && set -e

export SHELL_TRACE=false
export SSH_AGENT_OUTPUT="$HOME/.ssh/ssh-agent"
export SSH_TTL=86400 # twenty four hours in seconds

eval $(cat ${SSH_AGENT_OUTPUT})

source ~/workspaces/bernardolm/dotfiles/zsh/functions/log
for f in ~/workspaces/bernardolm/dotfiles/ssh/functions/*; do source $f; done

log start "ssh setup"

if ! which bc &>/dev/null; then
    echo -e "${CLR_RED} you need to install bc package: ${NO_COLOR}"
    echo -e "${CLR_RED} sudo apt-get install --no-install-recommends --yes bc ${NO_COLOR}"
    function bc() {
        echo $@
    }
fi

local pub_key=$(cat ~/.ssh/id_ed25519.pub)

ssh_envs

if [ "$(ssh_agents_running)" -gt 1 ] || [ "$(ssh_agent_loaded_keys)" -gt 1 ] || ! ssh_agent_my_key_is_loaded; then
    ssh_agent_kill
    ssh_envs
fi

if [ "$(ssh_agents_running)" -eq 0 ]; then
    ssh_agent_start
    ssh_envs
fi

if ! ssh_agent_my_key_is_loaded; then
    log info "adding my keys to ssh agent..."
    ssh-add #"$HOME/.ssh/id_ed25519"
fi

log debug "ssh keys loaded in agent:"
$SHELL_DEBUG && ssh-add -L

log finish "ssh setup"

# SHELL_DEBUG=$shell_debug_relay
