debug = True
exclude_rules = ['git_push']
history_limit = 9999999
no_colors = False
num_close_matches = 5
priority = {'sudo': 100, 'no_command': 9999}
require_confirmation = True
rules = ['sudo', 'no_command']
slow_commands = ['react-native', 'gradle']
wait_command = 10
wait_slow_command = 20
