services:

  docmost:

    container_name: docmost
    env_file:
      - $DOTFILES/docmost/.env
    environment:
      APP_SECRET: $APP_SECRET
      APP_URL: $APP_URL
      DATABASE_URL: $DATABASE_URL
      REDIS_URL: $REDIS_URL
    image: docmost/docmost:latest
    network_mode: bridge
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/data/docker-volumes/docmost:/app/data/storage
