#!/usr/bin/env bash

# shellcheck source=/dev/null
. "${DOTFILES}/zsh/functions/log"

log start "git setup"

[ ! -d "${DOTFILES}/git/modules" ] && mkdir -p "${DOTFILES}/git/modules"

log info "sanitizing git submodules"
git config --file "${DOTFILES}/.gitmodules" --list | tr ' ' '\n'
cat < .gitmodules | grep '\[submodule' | while read -r item; do
    name=$(echo "$item" | sed -E 's/.*"(.*)".*/\1/g')
    label=$(echo "$name" | xargs basename)
    path=$(git config --file ".gitmodules" --get "submodule.${name}.path")
    url=$(git config --file ".gitmodules" --get "submodule.${name}.url")

    echo "    submodule ${label} in ${path} by ${url}"

    if [ -d "${path}" ]; then
        echo "    updating..."
        git submodule update --init "${path}"
    else
        echo "    adding..."
        git submodule add --force "${url}" "${path}"
    fi
    echo -e "    done\n    ---"
done

git config --global --add safe.directory "$DOTFILES/git/modules/dotbot"

log finish "git setup"
