services:

  maestral:

    container_name: maestral
    env_file:
      - $DOTFILES/maestral/.env
    environment:
      TZ: America/Sao_Paulo
    image: maestraldbx/maestral:latest
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - $HOME/Dropbox:/dropbox-local-path
      - $HOME/Dropbox/linux/maestral/$HOSTNAME/.config:/dropbox/.config
      - $HOME/tmp/.maestral.cache:/dropbox-local-path/.maestral.cache
