services:

  maestral:

    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=$UID
        - GID=$GID
        - VERSION=$VERSION

    container_name: maestral
    env_file:
      - $DOTFILES/maestral/.env
    environment:
      TZ: America/Sao_Paulo
    image: bernardolm/maestral:latest
    # network_mode: bridge
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/data/docker-volumes/maestral:/dropbox
      - $HOME/Dropbox:/dropbox/Dropbox
