services:

  maestral:

    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=$UID
        - GID=$GID
        - VERSION=$VERSION
    # comment out "command" field below after first access
    # run after reconnect dropbox accout:
    # $ source $DOTFILES/maestral/start
    # command: maestral auth link --relink
    container_name: maestral
    env_file:
      - $DOTFILES/maestral/.env
    environment:
      TZ: America/Sao_Paulo
    image: bernardolm/maestral:latest
    # network_mode: bridge
    restart: unless-stopped
    # comment out "command" field below after first access
    # tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/data/docker-volumes/maestral:/dropbox
      - $HOME/sync:/dropbox/Dropbox
