services:

  maestral:

    container_name: maestral
    env_file:
      - $DOTFILES/maestral/.env
    environment:
      TZ: America/Sao_Paulo
    image: maestraldbx/maestral:latest
    # network_mode: bridge
    restart: unless-stopped
    user: $UID:$GID
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/data/docker-volumes/maestral:/dropbox
      - $HOME/Dropbox:/dropbox/Dropbox
