#!/usr/bin/env zsh

docker_container_name=maestral
docker_image_name=maestraldbx/maestral:latest

docker run \
    --name "${docker_container_name}" \
    --restart always \
    -d \
    -v "${HOME}/docker-volumes/${docker_container_name}:/dropbox" \
    -v "${HOME}/Dropbox:/dropbox-sync" \
    -v /etc/localtime:/etc/localtime:ro \
    "${docker_image_name}"
