#!/usr/bin/env zsh

local maestral_root="$DOTFILES/maestral"

docker compose \
    -f "$maestral_root/docker-compose.yml" \
    down --volumes --remove-orphans

SCRIPT_PATH=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "${SCRIPT_PATH}")

local github_repo="samschott/maestral"

curl -s \
    -o "$maestral_root/Dockerfile" \
    https://raw.githubusercontent.com/$github_repo/refs/heads/main/Dockerfile

local api_url="https://api.github.com/repos/$github_repo/releases/latest"

export VERSION
VERSION=$(curl -sL "${api_url}" | jq -r '.tag_name')

docker compose \
    -f "$maestral_root/docker-compose.yml" \
    up -d --build --force-recreate --remove-orphans
