#!/usr/bin/env bash

export TERM=xterm-256color

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "DOTFILES=$DOTFILES"

[ "${PWD}" != "$DOTFILES" ] \
    && echo "you NEED to be in $DOTFILES to continue..." \
    && exit 1

. "$DOTFILES/linux/pre-install"
. "$DOTFILES/zsh/zdotdir/.zshenv"

shell_debug_relay=${SHELL_DEBUG}
SHELL_DEBUG=true

. "$DOTFILES/zsh/functions/log"

log start "pristine setup"

. "$DOTFILES/git/install"
. "$DOTFILES/linux/install"
. "$DOTFILES/apt/install"
. "$DOTFILES/python/install"
. "$DOTFILES/ubuntu/post-install"

log finish "pristine setup"

SHELL_DEBUG=${shell_debug_relay}
