[project]
name = "dotfiles"
version = "0.0.0"
requires-python = ">=3.14"

[tool.unimport]
exclude = '\.venv|build|dist|lost-and-found'
gitignore = true
remove = true

[tool.yapf]
based_on_style = 'facebook'
column_limit = 120
continuation_align_style = 'valign-right'
continuation_indent_width = 2
indent_width = 2
use_tabs = true

[tool.yapfignore]
ignore_patterns = [
	'.venv',
	'lost-and-found',
	'lost-and-found/**',
	'**/.venv',
	'**/build',
	'**/dist',
	'build',
	'dist',
]

[tool.isort]
line_length = 120
skip = [
	'.venv',
	'lost-and-found',
	'lost-and-found/**',
	'**/.venv',
	'**/build',
	'**/dist',
	'build',
	'dist',
]

[tool.pylint]
exit-zero = true
# pylint espera expressão regular aqui, não glob
ignore-paths = [
	'^\.?/?\.venv/.*',
	'^\.?/?\.web/.*',
	'^\.?/?build/.*',
	'^\.?/?dist/.*',
	'.*/\.venv/.*',
	'.*/\.web/.*',
	'.*lost-and-found.*',
]
output-format = 'colorized'
recursive = true
max-line-length = 120

[tool.pylint.messages_control]
disable = [
	'bad-indentation',
	'broad-exception-caught',
	'import-error',
	'inherit-non-class',
	'invalid-name',
	'missing-class-docstring',
	'missing-function-docstring',
	'missing-module-docstring',
]

[tool.pytest]
addopts = ['-s', '-v', '-x', '--import-mode=importlib']
strict = true
testpaths = ['**/tests']
