#!/usr/bin/env zsh

function ssh_agent_kill() {
    log debug "killing and cleaning ssh agent..."
    ssh-agent -k 2>/dev/null || killall -9 ssh-agent 2>/dev/null
    rm -rf /tmp/ssh-* 2>/dev/null
    rm -f "${SSH_AGENT_OUTPUT}"
    unset SSH_AGENT_PID
    unset SSH_AUTH_SOCK
}
