#!/usr/bin/env zsh

function ssh_agent_kill() {
    log info "killing and cleaning ssh agent..."
    ssh-agent -k 2>/dev/null || killall -9 ssh-agent
    rm -rf /tmp/ssh-* 2>/dev/null
    echo "" > "${SSH_AGENT_OUTPUT}"
    unset SSH_AGENT_PID
    unset SSH_AUTH_SOCK
}
