#!/usr/bin/env zsh

function ssh_agent_state() {
    local ssh_add=$(ssh-add -L 2>&1)
    local ssh_agent_state="alive"

    case $ssh_add in
    "Error connecting to agent: No such file or directory")
        ssh_agent_state="no_connection"
        ;;
    "Error connecting to agent: Connection refused")
        ssh_agent_state="no_connection"
        ;;
    "Could not open a connection to your authentication agent.")
        ssh_agent_state="no_connection"
        ;;
    "The agent has no identities.")
        ssh_agent_state="empty"
        ;;
    esac

    echo $ssh_agent_state
}
