#!/usr/bin/env zsh

function ssh_agent_start() {
    log info "starting ssh agent..."

    ssh-agent -s -t ${SSH_TTL} | grep -v 'Agent pid' > ${SSH_AGENT_OUTPUT}
    chmod 600 "${SSH_AGENT_OUTPUT}"
    eval $(cat "${SSH_AGENT_OUTPUT}")
}
