#!/usr/bin/env zsh

function ssh_agent_start() {
    log debug "starting ssh agent..."

    local ssh_ttl=86400 # twenty four hours in seconds

    ssh-agent -s -t ${ssh_ttl} | grep -v 'Agent pid' > ${SSH_AGENT_OUTPUT_SCRIPT}
    chmod 600 "${SSH_AGENT_OUTPUT_SCRIPT}"
    source ${SSH_AGENT_OUTPUT_SCRIPT}
}
