#!/usr/bin/env zsh

starship || . $DOTFILES/starship/install

# export STARSHIP_CONFIG="${DOTFILES}/starship/tokyo-night.toml"
export STARSHIP_CONFIG="${DOTFILES}/starship/pastel-powerline.toml"

$SHELL_DEBUG && env STARSHIP_LOG=trace starship module rust
$SHELL_DEBUG && env STARSHIP_LOG=trace starship timings

eval "$(starship init zsh)"
