#!/usr/bin/env zsh

function network_reset_iptables() {
    CMDS=(ip6tables iptables)
    echo "running for ${CMDS[*]}"

    for p in "${CMDS[@]}"; do
        echo "running $p..."

        sudo "$p" -F
        sudo "$p" -F FORWARD
        sudo "$p" -F INPUT
        sudo "$p" -F OUTPUT
        sudo "$p" -P FORWARD ACCEPT
        sudo "$p" -P INPUT ACCEPT
        sudo "$p" -P OUTPUT ACCEPT
        sudo "$p" -t mangle -F
        sudo "$p" -t mangle -P FORWARD ACCEPT
        sudo "$p" -t mangle -P INPUT ACCEPT
        sudo "$p" -t mangle -P OUTPUT ACCEPT
        sudo "$p" -t mangle -P POSTROUTING ACCEPT
        sudo "$p" -t mangle -P PREROUTING ACCEPT
        sudo "$p" -t mangle -X
        sudo "$p" -t nat -F
        sudo "$p" -t nat -P OUTPUT ACCEPT
        sudo "$p" -t nat -P POSTROUTING ACCEPT
        sudo "$p" -t nat -P PREROUTING ACCEPT
        sudo "$p" -t nat -X
        sudo "$p" -X

        echo "finish $p"
    done

    sudo ufw --force reset
    sudo ufw --force enable

    echo "restoring rules"

    bash "${HOME}/sync/ufw-custom.txt"

    echo ""

    sudo ufw --force reload
    sudo ufw status numbered
}
