#!/usr/bin/env zsh

local __package=dropbox.py
local __bin_path="${HOME}/.local/bin/${__package}"

$SHELL_DEBUG && echo "__package=${__package}"
$SHELL_DEBUG && echo "__bin_path=${__bin_path}"

# https://www.dropbox.com/download?dl=packages/dropbox.py
# https://linux.dropbox.com/packages/dropbox.py

[ ! -f "${__bin_path}" ] \
    && SHELL_DEBUG=true log info "installing ${__package}" \
    && mkdir -p "$(dirname ${__bin_path})" \
    && curl -sL -o "${__bin_path}" https://www.dropbox.com/download?dl=packages/dropbox.py \
    && chmod u+x "${__bin_path}" \
    && ls -lah "${__bin_path}" \
    | log_is_command_success
