#!/usr/bin/env zsh

function zplug_reset() {
    start=$(date +%s%N)
    (zplug clean 2>/dev/null || true) \
        && (zplug clear 2>/dev/null || true) \
        && /bin/rm -rf ~/.zplug ~/.cache/zplug \
        && export ZPLUG_LOG_LOAD_SUCCESS=true \
        && export ZPLUG_LOG_LOAD_FAILURE=true \
        && export ZPLUG_VERBOSE="--verbose"
    echo "$(elapsed_time $start) zplug_reset"
}
