-- local random_theme = require("theme")
-- local wezterm = require("wezterm")

-- wezterm.on('update-right-status', function(window, pane)
-- 	local scheme = random_theme.current_scheme_name(window)
-- 	if scheme then
-- 		window:set_right_status(wezterm.format {
-- 			{ Text = '  ' .. scheme .. '  ' },
-- 		})
-- 	else
-- 		window:set_right_status('')
-- 	end
-- end)
