# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

blocks:
- alignment: left
  segments:
  - type: text
    style: diamond
    leading_diamond: ""
    foreground: "#ffffff"
    background: "#cc3802"
    template: "{{ if .Env.PNPPSHOST }}  {{ .Env.PNPPSHOST }} {{ end }}"
  - type: text
    style: powerline
    foreground: "#ffffff"
    background: "#047e84"
    powerline_symbol: ""
    template: "{{ if .Env.PNPPSSITE }}  {{ .Env.PNPPSSITE }}{{ end }}"
  - type: text
    style: diamond
    trailing_diamond: ""
    foreground: "#ffffff"
    background: "#047e84"
    template: "{{ if .Env.PNPPSSITE }} {{ end }}"
  type: rprompt
- alignment: left
  segments:
  - background: "#9A348E"
    foreground: "#ffffff"
    leading_diamond: ""
    style: diamond
    template: "{{ .UserName }} "
    type: session
  - background: "#DA627D"
    foreground: "#ffffff"
    powerline_symbol: ""
    properties:
      style: folder
    style: powerline
    template: " {{ .Path }} "
    type: path
  - background: "#FCA17D"
    foreground: "#ffffff"
    powerline_symbol: ""
    properties:
      branch_icon: ''
      fetch_stash_count: true
      fetch_status: false
      fetch_upstream_icon: true
    style: powerline
    template: " ➜ ({{ .UpstreamIcon }}{{ .HEAD }}{{ if gt .StashCount 0 }}  {{ .StashCount
      }}{{ end }}) "
    type: git
  - background: "#86BBD8"
    foreground: "#ffffff"
    powerline_symbol: ""
    style: powerline
    template: "  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{
      .Full }} "
    type: node
  - background: "#33658A"
    foreground: "#ffffff"
    properties:
      time_format: '15:04'
    style: diamond
    template: " ♥ {{ .CurrentDate | date .Format }} "
    trailing_diamond: ""
    type: time
  type: prompt
final_space: true
version: 2
