#!/usr/bin/env zsh

function git_commit_last_with_file() {
    FILE=$1

    LOG=$2
    if [[ "$LOG" == "" ]]; then
        echo "seeking last commit with file $FILE..."
        LOG="$USER_TMP/git_commit_last_with_file_"
        LOG+=$(date +"%Y%m%d%H%M%S")
        LOG+=".log"
        touch $LOG
    fi

    LAST_COMMIT=$3

    CURRENT_COMMIT=$(git_current_commit)
    echo $CURRENT_COMMIT >> $LOG

    if [ -f $1 ]; then
        echo "file yet found, going head..."
        go_to_git_next_commit
        if [[ "$?" = "1" ]]; then
            echo "git_next_commit returns error, retrying"
            sleep 3
        fi
        git_commit_last_with_file $FILE $LOG $CURRENT_COMMIT
    else
        echo "file no more found, going back to $LAST_COMMIT"
        git_checkout_pristine $LAST_COMMIT 1> /dev/null 2>&1
        echo "finish"
    fi
}
