services:

  mosquitto:

    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=$UID

    container_name: mosquitto
    env_file:
      - $DOTFILES/mosquitto/.env
    environment:
      TZ: America/Sao_Paulo
    image: bernardolm/mosquitto:latest
    network_mode: bridge
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/data/docker-volumes/mosquitto/data:/mosquitto/data
      - /mnt/data/docker-volumes/mosquitto/log:/mosquitto/log
      - $DOTFILES/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
