services:

  mosquitto:

    container_name: mosquitto
    env_file:
      - $DOTFILES/mosquitto/.env
    environment:
      TZ: America/Sao_Paulo
    image: $GITHUB_USER/mosquitto:latest
    network_mode: bridge
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/data/docker-volumes/mosquitto/data:/mosquitto/data
      - /mnt/data/docker-volumes/mosquitto/log:/mosquitto/log
      - $DOTFILES/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
