#!/usr/bin/env zsh

docker run \
    --restart always \
    -d \
    --name mosquitto \
    -p 1883:1883 \
    -p 9001:9001 \
    -v "$DOTFILES/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro" \
    -v "$SYNC_DOTFILES/mosquitto:/mosquitto" \
    eclipse-mosquitto:2.0.17
 