#!/usr/bin/env zsh

docker_container_name=mosquitto
docker_image_name="${GITHUB_USER}/${docker_container_name}:latest"

echo "docker_container_name=$docker_container_name"
echo "docker_image_name=$docker_image_name"

if [ -z "$(docker images -q "${docker_image_name}" 2> /dev/null)" ]; then
    uid=$(id -u)

    docker build \
        --build-arg "muid=${uid}" \
        -f "${DOTFILES}/${docker_container_name}/Dockerfile" \
        -t "${docker_image_name}" \
        "${DOTFILES}/${docker_container_name}"
fi

docker compose up -d
docker compose logs -f ${docker_container_name}
