#!/usr/bin/env zsh

function apt_keys_recovery() {
    # shell_debug_relay=$SHELL_DEBUG
    # SHELL_DEBUG=true

    log start "recovering gpg keys absent"

    local file

    ## 1password
    function 1password() {
        log info "1password"

        curl -sS https://downloads.1password.com/linux/keys/1password.asc | \
            sudo gpg --yes --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg

        [ -f /etc/apt/sources.list.d/1password.list ] && sudo rm -f /etc/apt/sources.list.d/1password.list

        echo -n 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg]' \
            'https://downloads.1password.com/linux/debian/amd64 stable main' | \
            sudo tee /etc/apt/sources.list.d/1password.list &>/dev/null

        sudo mkdir -p /etc/debsig/policies/AC2D62742012EA22/

        curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | \
            sudo tee /etc/debsig/policies/AC2D62742012EA22/1password.pol &>/dev/null

        sudo mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22

        curl -sS https://downloads.1password.com/linux/keys/1password.asc | \
            sudo gpg --yes --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
    }

    ## docker
    file=/etc/apt/trusted.gpg.d/docker.gpg
    if [ ! -f $file ]; then
        log info "docker"
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo \
            gpg --yes --dearmor --output $file
    fi

    ## google cloud platform
    file=/etc/apt/trusted.gpg.d/cloud.google.gpg
    if [ ! -f $file ]; then
        log info "google cloud"
        curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo \
            gpg --yes --dearmor --output $file
    fi

    declare -a servers=(
        "keyserver.ubuntu.com"
        "keys.openpgp.org"
        "keys.gnupg.net"
        "pgp.mit.edu"
    )

    [ -f /etc/apt/trusted.gpg ] && sudo /bin/rm /etc/apt/trusted.gpg

    sudo apt-get update 2>/dev/null | sed -nr 's/^.*NO_PUBKEY\s(\w{16}).*$/\1/p' | sort | uniq | while read -r key; do
        log info "${key}: no pubkey found"

        if [ "$key" == "AC2D62742012EA22" ]; then
            1password
        else
            for server in "${servers[@]}"; do
                log info "${key}: trying recover key from ${server}"
                sudo apt-key adv --keyserver ${server} --recv-keys ${key} &>/dev/null && log info "${key}: OK" && break || log error "${key}: failed"
            done

            sudo apt-key export ${key} 2>/dev/null | sudo gpg --batch --yes --dearmour -o /etc/apt/trusted.gpg.d/${key}.gpg
        fi

        log info "${key}: done"
    done

    log finish "gpg keys absent recovered"

    # SHELL_DEBUG=$shell_debug_relay
}
