#!/usr/bin/env zsh

log_starting 'docker'

if [ ! ${DOCKER} ]; then
    [ $(/bin/cat /etc/group | grep docker | wc -l | bc) -eq 0 ] && sudo groupadd docker && newgrp docker
    [ $(getent group docker | grep $USER | wc -l | bc) -eq 0 ] && sudo usermod -aG docker $USER
fi

log_finishing 'docker'
