#!/usr/bin/env bash

log start 'docker start containers'

CURRENT_PWD=$(pwd)

found_containers=""

find "$DOTFILES" -name 'docker-compose.yml' | while read -r file; do
    BASE_PATH=$(basename $(dirname $file))
    found_containers="$found_containers $BASE_PATH"
    # cd $BASE_PATH
    # docker compose up -d
    # echo "\n"
done

log info "found docker compose files for:$found_containers"

echo ""

declare -a containers=(
    grafana
    influxdb
    loki
    maestral
    mariadb
    mosquitto
    redis
)

echo "DESTROY=$DESTROY"

for container in "${containers[@]}"; do
    [[ "$DESTROY" == "yes" ]] && (docker stop "$container" || true)
    [[ "$DESTROY" == "yes" ]] && (docker rm "$container" || true)
    if [ -f "$DOTFILES/$container/start" ]; then
        echo "Running $container start script"
        bash "$DOTFILES/$container/start"
    else
        echo "No start script found for $container, using docker-compose command"
        docker compose -f "$DOTFILES/$container/docker-compose.yml" up -d
    fi

    echo "done with $container"
done

# cd $CURRENT_PWD

docker container ls -a --format "table {{.Names}}\t{{.State}}\t{{.Ports}}"

log finish 'docker start containers'
