#!/usr/bin/env zsh

brew install zplug

# curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh

zplug "molovo/revolver", \
  as:command, \
  use:revolver
