#!/usr/bin/env zsh

log start "zplug install"

if ! [[ -d "${HOME}/.zplug" ]]; then
    curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
fi

while true; do
    if [ -f "${ZPLUG_HOME}/init.zsh" ]; then
        source "${ZPLUG_HOME}/init.zsh"
        break
    fi
    echo "waiting install..."
    sleep 1
done

log finish "zplug install"
