#!/usr/bin/env zsh

log start "zplug start"

. "${DOTFILES}/zplug/install"

while true; do
    if [ -f "${ZPLUG_HOME}/init.zsh" ]; then
        log debug "sourcing zplug init"
        source "${ZPLUG_HOME}/init.zsh"
        break
    fi
    log debug "waiting zplug be installed..."
    sleep 1
done

zplug clear

local plugins_list=($(zsh_plugins_list))

for p in $plugins_list; do
    log debug "zplug: $p"
    zplug "$p"
done

if ! zplug check; then
    log warn "zplug: installing new plugins"
    $SHELL_DEBUG && zplug install --verbose || zplug install
fi

log info "zplug: loading"
$SHELL_DEBUG && zplug load --verbose || zplug load

# zplug "dracula/zsh", as:theme
zplug "dracula/zsh-syntax-highlighting"
zplug "zsh-users/zsh-syntax-highlighting", defer:2

log finish "zplug start"
