services:

  nextcloud:

    container_name: nextcloud
    env_file:
      - $DOTFILES/nextcloud/.env
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_USER: $MYSQL_USER
      NEXTCLOUD_ADMIN_PASSWORD: NEXTCLOUD_ADMIN_PASSWORD
      NEXTCLOUD_ADMIN_USER: NEXTCLOUD_ADMIN_USER
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      REDIS_HOST_PASSWORD: $REDIS_HOST_PASSWORD
      REDIS_HOST_PORT: $REDIS_HOST_PORT
      REDIS_HOST: $REDIS_HOST
      TZ: America/Sao_Paulo
    image: nextcloud:stable
    network_mode: bridge
    ports:
      - 8080:80
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/data/docker-volumes/nextcloud/html:/var/www/html
