#!/usr/bin/env zsh

docker_container_name=nextcloud
docker_image_name="${GITHUB_USER}/${docker_container_name}:latest"

echo "docker_container_name=$docker_container_name"
echo "docker_image_name=$docker_image_name"



    # -d \
    # --restart always \
docker run \
    --name "${docker_container_name}" \
    -p 8080:8080 \
    -v "/mnt/data/docker-volumes/${docker_container_name}/data:/mosquitto/data" \
    -v /etc/localtime:/etc/localtime:ro \
    "${docker_image_name}"
