#!/usr/bin/env zsh

function duckdns_update_host_of_wsl() {
    log debug "WSL_SYSTEM=${WSL_SYSTEM}"

    if [ "${WSL_SYSTEM}" != 'true' ]; then
        log warn "you are not in WSL"
        return
    fi

    host_domain=$(hostname.exe | tr -d ' |\r')
    host_ip=$(netsh.exe interface ipv4 show addresses | grep "IP" | grep "192.168.0." | cut -d: -f2 | tr -d ' |\r')

    duckdns_update "${GITHUB_USER}--${host_domain}" "${host_ip}"
}
