#!/usr/bin/env zsh

function duckdns_update_wsl_host() {
    PATH=/mnt/c/WINDOWS/system32/:$PATH

    host_domain=$(hostname.exe | tr -d ' |\r')
    host_ip=$(netsh.exe interface ipv4 show addresses | grep "IP" | grep "192.168" | cut -d: -f2 | tr -d ' |\r')

    duckdns_update "${GITHUB_USER}--${host_domain}" "${host_ip}"
}
