#!/usr/bin/env zsh

function duckdns_update_wsl_host() {
    log_start "duckdns host WSL IP update"

    host_domain=$(hostname.exe | tr -d ' |\r')
    host_ip=$(netsh.exe interface ipv4 show addresses | grep "IP" | grep "192.168" | cut -d: -f2 | tr -d ' |\r')

    duckdns_update ${host_domain} ${host_ip}
}
