#!/usr/bin/env zsh

function duckdns_update_public() {
    log debug "DUCKDNS_DOMAIN=${DUCKDNS_DOMAIN}"
    log debug "IP_PUBLIC_NOW=${IP_PUBLIC_NOW}"
    log debug "IP_PUBLIC_WORK=${IP_PUBLIC_WORK}"

    if [ "${IP_PUBLIC_NOW}" = "${IP_PUBLIC_WORK}" ]; then
        log warn "${DUCKDNS_DOMAIN} with ${IP_PUBLIC_WORK} does not need to update"
        return
    fi

    duckdns_update "${DUCKDNS_DOMAIN}" "${IP_PUBLIC_NOW}"
}
