#!/usr/bin/env zsh

function duckdns_update_host_of_wsl() {
    log debug "WSL_SYSTEM=${WSL_SYSTEM}"

    if [ "${WSL_SYSTEM}" != 'true' ]; then
        log warn "you are not in WSL"
        return
    fi

    host_domain=$(hostname.exe | tr -d ' |\r')
    log debug "host_domain=${host_domain}"
    log debug "IP_RANGE_PREFIX=${IP_RANGE_PREFIX}"

    host_ip=$(netsh.exe interface ipv4 show addresses | grep "IP" | grep "${IP_RANGE_PREFIX}" | cut -d: -f2 | tr -d ' |\r')
    log debug "host_ip=${host_ip}"

    if [ -z "${host_ip}" ]; then
        log error "host IP is empty"
        return 1
    fi

    duckdns_update "${GITHUB_USER}--${host_domain}" "${host_ip}"
}
