#!/usr/bin/env zsh

function duckdns_update_host() {
    domain_suffix=""

    if [ "${WSL_SYSTEM}" = 'true' ]; then
        domain_suffix="-wsl"
    fi

    duckdns_update "${GITHUB_USER}--${HOSTNAME}${domain_suffix}" "${IP_CURRENT}"
}
