#!/bin/sh

echo "> darwin start"

PATH+=":/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
PATH+=":/Library/Frameworks/Python.framework/Versions/Current/bin"
PATH+=":/home/linuxbrew/.linuxbrew/bin"
PATH+=":/opt/homebrew/bin"
PATH+=":/opt/homebrew/opt/curl/bin"
PATH+=":/opt/homebrew/opt/libpq/bin"
PATH+=":/opt/homebrew/opt/openssl@3.6/bin"
export PATH

export HOMEBREW_NO_ENV_HINTS ; HOMEBREW_NO_ENV_HINTS=1
export HOSTNAME ; HOSTNAME=$(hostname -s)
export IP_CURRENT ; IP_CURRENT=$(ipconfig getifaddr en0 || ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}' | head -1)
export IS_DARWIN ; IS_DARWIN=1
export LDFLAGS ; LDFLAGS+=" -I /opt/homebrew/opt/openssl@3.6/include -L /opt/homebrew/opt/openssl@3.6/lib "
export SSH_AUTH_SOCK ; SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock

alias cat='bat'
alias mv='/bin/mv'

echo "> darwin finish"
