#!/bin/sh

echo "> running darwin start"

export HOSTNAME ; HOSTNAME=$(hostname -s)
export IP_CURRENT ; IP_CURRENT=$(ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}' || ipconfig getifaddr en0)
export IS_DARWIN ; IS_DARWIN=true
export LDFLAGS ; LDFLAGS+=" -I /opt/homebrew/opt/openssl@3.6/include -L /opt/homebrew/opt/openssl@3.6/lib "

PATH+=":/opt/homebrew/bin"
PATH+=":/opt/homebrew/opt/curl/bin"
PATH+=":/opt/homebrew/opt/libpq/bin"
PATH+=":/opt/homebrew/opt/openssl@3.6/bin"
PATH+=":/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
PATH+=":/Library/Frameworks/Python.framework/Versions/Current/bin"
PATH+=":$HOME/sync/bin"

alias cat='bat'
