#!/usr/bin/env zsh

function antigen_purge() {
    log_info "antigen_purge"

    find "$HOME" -maxdepth 2 -name '*.zcompdump*' -delete -true
    find "$HOME" -maxdepth 2 -name '*.zwc' -delete -true

    rm -rf "$ANTIGEN_PATH"
    rm -rf "$ANTIGEN_WORKDIR"

    compinit
}
