#!/usr/bin/env zsh

function antigen_setup() {
    log_info "antigen_setup"

    # shellcheck source=/dev/null
    # . "${DOTFILES}/zsh/functions/shell.zsh"

    antigen_start

    log_debug "antigen use oh-my-zsh"
    antigen use oh-my-zsh

    local plugins
    plugins=$(file_lines_2_inline "${DOTFILES}/zsh/plugins.txt")
    log_info "zsh plugins: $plugins"
    antigen bundle "$plugins"

    local plugins
    plugins=$(file_lines_2_inline "${DOTFILES}/ohmyzsh/plugins.txt")
    log_info "ohmyzsh plugins: $plugins"
    antigen bundle "$plugins"

    log_debug "antigen theme robbyrussell"
    antigen theme robbyrussell

    log_debug "antigen apply"
    antigen apply

    log_debug "antigen cache-gen"
    antigen cache-gen
}
