#!/usr/bin/env zsh

function antigen_purge() {
    log info "antigen_purge"

    find "$HOME" -maxdepth 1 -name '*.zcompdump*' -delete -true # completion cache
    find "$HOME" -maxdepth 5 -name '*.zwc' -delete -true

    rm -rf "$ANTIGEN_PATH"
    rm -rf "$ANTIGEN_WORKDIR"

    compinit
}
