"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$line_break\
[](color_section_1)\
$shell\
$os\
[ ](fg:color_section_1 bg:color_section_2)\
$username\
$hostname\
$localip\
$jobs\
[ ](fg:color_section_2 bg:color_section_3)\
$aws\
$azure\
$container\
$direnv\
$docker_context\
$docker\
$gcloud\
$nats\
$sudo\
[ ](fg:color_section_3 bg:color_section_4)\
$git_branch\
$git_commit\
$git_metrics\
$git_state\
$git_status\
$fossil_branch\
$fossil_metrics\
[ ](fg:color_section_4 bg:color_section_5)\
$buf\
$c\
$cmake\
$cobol\
$conda\
$crystal\
$custom\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$fortran\
$gleam\
$golang\
$gradle\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$kubernetes\
$lua\
$meson\
$mise\
$nim\
$nix_shell\
$nodejs\
$ocaml\
$opa\
$openstack\
$package\
$perl\
$php\
$pijul_channel\
$pixi\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$red\
$rlang\
$ruby\
$rust\
$scala\
$shlvl\
$singularity\
$solidity\
$spack\
$swift\
$terraform\
$typst\
$vagrant\
$vcsh\
$vlang\
$zig\
[ ](fg:color_section_5 bg:color_section_6)\
${custom.atuin_history_lines}\
[ ](fg:color_section_6 bg:color_section_7)\
$time\
$cmd_duration\
[ ](fg:color_section_7 bg:color_section_8)\
$status\
[ ](fg:color_section_8)\
$character\
"""

add_newline = true
palette = 'my_pallete'
scan_timeout = 10

[aws]
disabled = true
symbol = '🅰 '
style = ''

[aws.region_aliases]
ap-southeast-2 = 'au'
us-east-1 = 'va'

[aws.profile_aliases]
CompanyGroupFrobozzOnCallAccess = 'Frobozz'

[azure]
disabled = true
symbol = '󰠅 '
style = ''

[azure.subscription_aliases]
very-long-subscription-name = 'vlsn'

[c]
disabled = true
symbol = " "
style = ''

[character]
disabled = true
error_symbol = '⚠'
format = '$symbol'
success_symbol = '…'

[cmd_duration]
format = '[~$duration ]($style)'
min_time = 1_00
style = 'bg:color_section_7 fg:color_foreground_text_light'

[conda]
disabled = true
style = ''

[cpp]
disabled = true
symbol = " "
style = ''

[custom.atuin_history_lines]
command = "$HOME/dotfiles/cli/starship/functions/starship_atuin_history_lines"
disabled = false
format = '[$symbol$output ]($style)'
style = 'bg:color_section_6 fg:color_foreground_text_light'
symbol = '≣'
when = true

[custom.wsl]
disabled = true
when='[[ $(grep -i Microsoft /proc/version) ]]'
style = ''

[dart]
disabled = true

[deno]
disabled = true
style = ''

[directory]
disabled = false
truncate_to_repo = false
truncation_length = 0
style = ''

[directory.substitutions]
"Developer" = "󰲋 "
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "

[docker_context]
disabled = false
symbol = ""
style = ''

[dotnet]
disabled = true
heuristic = false
symbol = '🥅 '
style = ''

[elixir]
disabled = true
symbol = '🔮 '
style = ''

[fossil_branch]
disabled = false
symbol = '🦎 '
truncation_length = 4
truncation_symbol = ''
style = ''

[fossil_metrics]
disabled = false

[gcloud]
disabled = false
format = '[$symbol:$region ]($style)'
style = 'bg:color_section_3 fg:color_foreground_text_dark'
symbol = 'gcp'

[gcloud.project_aliases]
very-long-project-name = 'vlpn'

[gcloud.region_aliases]
us-central1 = 'uc1'

[git_branch]
format = '[$symbol$branch ]($style)'
disabled = false
style = 'bg:color_section_4 fg:color_foreground_text_dark'

[git_commit]
commit_hash_length = 4
disabled = false
style = 'bg:color_section_4 fg:color_foreground_text_dark'

[git_metrics]
disabled = true

[git_state]
disabled = false
style = 'bg:color_section_4 fg:color_foreground_text_dark'

[git_status]
disabled = true
style = 'bg:color_section_4 fg:color_foreground_text_dark'

[golang]
format = '[$symbol$version$mod_version ]($style)'
disabled = false
symbol = ""
style = 'bg:color_section_5 fg:color_foreground_text_dark'

[haskell]
disabled = true
symbol = ""
style = ''

[hostname]
# format = '[@](bold $style)[$ssh_symbol$hostname]($style)'
disabled = false
format = '[$ssh_symbol$hostname](bold $style)'
ssh_only = false
style = 'bg:color_section_2 fg:color_foreground_text_light'

[java]
disabled = true
symbol = ""
style = ''

[jobs]
disabled = false
format = '[$number]($style)'
style = ''

[kotlin]
disabled = true
symbol = ""
style = ''

[kubernetes]
detect_files = ['k8s']
disabled = true
style = ''

[line_break]
disabled = false

[localip]
disabled = false
ssh_only = false
style = 'bg:color_section_2 fg:color_foreground_text_light'
format = '[\($localipv4\) ](italic $style)'

[lua]
disabled = false
style = ''

[memory_usage]
disabled = true
threshold = -1
style = ''

[netns]
disabled = true
symbol = '🌐 '
style = ''

[nodejs]
disabled = false
symbol = ""
style = ''

[os]
format = "[${custom.wsl}$symbol ]($style)"
disabled = false
style = 'bg:color_section_1 fg:color_foreground_text_light'

[os.symbols]
Alpine = ""
Debian = ""
Linux = ""
Macos = ""
Raspbian = ""
Ubuntu = "󰕈"
Unknown = ""
Windows = "󰍲"

[package]
disabled = false
style = ''

[palettes.my_pallete]
color_foreground_text_dark = '#001219'
color_foreground_text_light = '#E9D8A6'
color_section_1 = '#005f73'
color_section_2 = '#0a9396'
color_section_3 = '#94d2bd'
color_section_4 = '#e9d8a6'
color_section_5 = '#ee9b00'
color_section_6 = '#ca6702'
color_section_7 = '#bb3e03'
color_section_8 = '#ae2012'

[php]
disabled = false
symbol = ""
style = ''

[pixi]
disabled = true
style = ''

[python]
detect_env_vars = ["VIRTUAL_ENV"]
disabled = false
pyenv_version_name = true
symbol = ""
style = 'bg:color_section_5 fg:color_foreground_text_dark'
format = '[$symbol$version$virtualenv ]($style)'

[ruby]
disabled = true
symbol = '🔺 '
style = ''

[rust]
disabled = true
symbol = ""
style = ''

[shell]
disabled = false
format = '[󱆃$indicator ]($style)'
style = 'bg:color_section_1 fg:color_foreground_text_light'
zsh_indicator = 'z'

[singularity]
disabled = false
style = ''

[status]
disabled = false
format = '[$symbol]($style)'
style = 'bg:color_section_8 fg:color_foreground_text_light'
success_symbol = '…'
symbol = '⚠ $status'

[sudo]
allow_windows = true
disabled = false
symbol = '👩‍💻 '
style = ''

[terraform]
disabled = false
style = ''

[time]
format = '[$time ]($style)'
disabled = false
style = 'bg:color_section_7 fg:color_foreground_text_light'

[username]
disabled = true
format = '[$user]($style)'
show_always = true
style_user = 'bg:color_section_2 fg:color_foreground_text_light'
