permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.0.12:1883
  user: zigbee2mqtt
  include_device_information: true
  client_id: zigbee2mqtt
  force_disable_retain: true
serial:
  port: /dev/ttyUSB0
  disable_led: true
  adapter: zstack
frontend: {}
homeassistant:
  legacy_entity_attributes: true
devices: devices.yaml
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  cache_state: true
  cache_state_persistent: false
  cache_state_send_on_startup: false
  last_seen: ISO_8601_local
  log_debug_to_mqtt_frontend: true
  log_namespaced_levels:
    z2m:mqtt: warning
device_options:
  legacy: false
availability: {}
