# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# [character]
# format = 'out $symbol'
# success_symbol = "🥳  "
# error_symbol = "🤬  "

[custom.wsl]
symbol = '🪟 '
when='[[ $(grep -i Microsoft /proc/version) ]]'

[os]
disabled=false
format = "[on (${custom.wsl} $symbol $name $codename )]($style)"
# style = "bold blue"
style = "bg:color_orange fg:color_fg0"

[hostname]
format = 'at [$ssh_symbol$hostname]($style) '
ssh_only = false
ssh_symbol = '📡 '
style = 'bold red'

[aws]
disabled = true

[buf]
disabled = true

[c]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[fennel]
disabled = true

[fossil_branch]
disabled = true

[guix_shell]
disabled = true

[haskell]
disabled = true

[haxe]
disabled = true

[hg_branch]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[lua]
disabled = true

[meson]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[ocaml]
disabled = true
