[palettes.custom1]
color_fg0 = '#ffffff'
color_bg1 = '#0a070c'
color_bg3 = '#140f17'
color_blue = '#242835'
color_aqua = '#293338'
color_green = '#252b27'
color_orange = '#52221a'
color_purple = '#332238'
color_red = '#66151e'
color_yellow = '#614d3f'