#!/usr/bin/env /bin/zsh

export TERM=xterm-256color

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "DOTFILES=$DOTFILES"

[ "${PWD}" != "$DOTFILES" ] \
    && echo "you NEED to be in $DOTFILES to continue..." \
    && exit 1

. "$DOTFILES/linux/pre-install"
. "$DOTFILES/zsh/zdotdir/.zshenv"

. "$DOTFILES/zsh/functions/log"

log start "pristine setup"

. "$DOTFILES/git/install"
. "$DOTFILES/linux/install"
. "$DOTFILES/apt/install"
. "$DOTFILES/python/install"
. "$DOTFILES/ubuntu/post-install"

log finish "pristine setup"
