#!/usr/bin/env zsh

unsetopt correct_all # try to correct the spelling of arguments too
unsetopt hup # don't kill bg process when terminal is killed or exited
unsetopt nomatch # if a pattern for filename generation has no matches, print an error
unsetopt notify # report the status of background jobs immediately,
