#!/usr/bin/env zsh

# zstyle ':compinstall'  filename "${HOME}/.zshrc"
# zstyle ':completion:*:complete:ls:*:*' verbose no
# zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
# zstyle ':completion:*' menu select
# zstyle ':completion:*' verbose yes
