#!/usr/bin/env zsh

log start "ohmyzsh install"

if [ ! -d "${ZSH}" ]; then
    SHELL_DEBUG=true $SHELL_DEBUG && \
        log info "installing (downloading) oh-my-zsh"

    curl -fsSL "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh" | \
        KEEP_ZSHRC=yes RUNZSH=no CHSH=no bash

    SHELL_DEBUG=true log warn "change default shell to zsh? input password"
    chsh -s $(which zsh)
fi

log finish "ohmyzsh install"
