#!/usr/bin/env zsh

fpath=( "$DOTFILES/ohmyzsh/functions" $fpath )
autoload -Uz ${fpath[1]}/*(:t)

. "$DOTFILES/ohmyzsh/install"

. $ZSH/oh-my-zsh.sh

plugins=($(ohmyzsh_plugins_list))
log_info "oh-my-zsh plugins to load '$plugins'"

# Downloading docker completions
ohmyzsh_docker_completions

chmod +x ~/.local/bin/register-python-argcomplete
