#!/usr/bin/env zsh

fpath=( "${DOTFILES}/ohmyzsh/functions" $fpath )
autoload -Uz ${fpath[1]}/*(:t)

. "${DOTFILES}/ohmyzsh/install"

plugins=($(ohmyzsh_plugins_list))
$SHELL_DEBUG && echo "oh-my-zsh plugins to load: '$plugins'"

zstyle ':omz:lib:directories' aliases no
zstyle ':omz:lib:theme-and-appearance' aliases no

. "${ZSH}/oh-my-zsh.sh"

# Downloading docker completions
ohmyzsh_docker_completions
