#!/usr/bin/env zsh

function auto-ls-custom_function() {
    $SHELL_DEBUG && echo -n $funcstack[1]":\n"

    local files=$(find . -maxdepth 1 -type f | wc -l)
    local hiddenFiles=$(find . -maxdepth 1 -type f | grep "./." | wc -l)
    local folders=$(find . -maxdepth 1 -type d | wc -l)

    SHELL_DEBUG=true log info "there are $PURPLE $files $NC$CYAN files ($ROSE $hiddenFiles $NC$CYAN hidden) and $PURPLE $folders $NC$CYAN folders in this path."
}
