#!/usr/bin/env zsh

function auto-ls-custom_function() {
    echo "auto-ls-custom_function:"

    $SHELL_DEBUG && echo -n $funcstack[1]":\n"

    shell_folder_summary

    /usr/bin/exa \
        --blocks \
        --classify \
        --color-scale \
        --color=always \
        --group-directories-first \
        --icons \
        --inode \
        --level=2 \
        --links \
        --list-dirs \
        --octal-permissions \
        --tree | head -30
}
