#!/usr/bin/env zsh

function caller() {
    if [[ $BASH_VERSION ]]; then
        local file=${BASH_SOURCE[1]} func=${FUNCNAME[1]} line=${BASH_LINENO[0]}
    else
        local _file="$(tput setab 237)$(tput setaf 255)"
        local _reset_color="\e[0m"
        local _stack=""

        local _sep="$(tput setab 237)$(tput setaf 14)\e[1m>${_reset_color}"

        for f in $funcfiletrace; do
            if [[ ! $f =~ "/log_" ]]; then
                f=$(basename $f)
                if [[ ! -z $_stack ]]; then
                    _stack="${_file} $f ${_reset_color}${_sep}${_file}${_stack}${_reset_color}"
                else
                    _stack="${_file} $f ${_reset_color}"
                fi
            fi
        done

        printf "${_stack}${_reset_color}"
    fi
}
