#!/usr/bin/env zsh

function chmod_reset() {
    # shell_debug_relay=$SHELL_DEBUG
    # SHELL_DEBUG=true

    $SHELL_DEBUG && set -x

    sudo chmod -cR 600 $1
    sudo chmod -R u+X $1
    sudo chown -cR $USER:$USER $1

    patterns=(
        "*.AppImage"
        "*.py"
        "*.sh"
        "/bin/"
        "install-pristine"
        "install"
        "post-install"
        "post-setup"
        "pre-install"
        "pre-setup"
        "setup"
        "start"
    )
    # for p in "${patterns[@]}"; do
    #     sudo find "$1" -name "$p" -exec sudo chmod u+x {} \;
    # done

    # SHELL_DEBUG=$shell_debug_relay
    $SHELL_DEBUG && set +x
}
