#!/usr/bin/env zsh

function chrome_bookmarks_backup() {
    [ ! -d "${HOME}/sync/chrome/bookmarks" ] && \
        mkdir -p "${HOME}/sync/chrome/bookmarks"
    find ~/.config/google-chrome -name '*Bookmarks*' | while read -r item; do
        slug=$(echo "$item" | sed -e 's/[ \/.]/_/g')
        cp "$item" "${HOME}/sync/chrome/bookmarks/${slug}_${NOW}"
    done
}
