#!/usr/bin/env zsh

function conky_start() {
    unset DEBUG

    local attrs="--quiet --daemonize"
    if [ ! -z "$DEBUG" ]; then
        attrs=" -D "
    fi

    local cmd="conky ${attrs} --config"

    # eval ${cmd} "$DOTFILES/.config/conky/left.conf"
    eval "${cmd} $DOTFILES/.config/conky/right.conf"
}
