#!/usr/bin/env zsh

function docker_images_sanitize() {
    echo "removing docker images"
    docker_install_check || return
    docker_images_list | while read -r id; do
        echo "removing $id"
        docker_image_remove ${id} || continue
    done
}
