#!/usr/bin/env zsh

function docker_install_sanitize() {
    echo "removing docker installation"

    if [[ $(docker_running_check) -eq 1 ]]; then
        echo "docker is running"

        docker_content_sanitize

        yes | docker system prune --all --volumes --force

        sudo systemctl stop docker.socket
        sudo systemctl stop docker.service

        while [[ $(docker_running_check) -eq 1 ]]; do
            echo "waiting docker be stopped..."
            sleep 1
        done
    fi

    if [[ "$1" != "no-purge" ]]; then
        echo "finding docker installation..."
        if [[ $(docker_install_check) -eq 1 ]]; then
            echo "purging existent docker ubuntu package"
            echo "\033[0;36m"
            sudo apt purge '^docker' containerd runc --yes 2>/dev/null
            sudo apt autoremove --purge --yes
            echo "\033[0m"
        else
            echo "no docker install found"
        fi
    fi

    dockerdns_sanitize_vestiges
    docker_install_config_files_sanitize
    docker_local_ip_sanitize
}
