#!/usr/bin/env zsh

function docker_containers_sanitize() {
    echo "removing docker containers"
    docker_install_check || return
    docker_containers_list | while read -r id; do
        echo "removing $id"
        docker_contaier_remove "${id}" || continue
    done
}
