#!/usr/bin/env zsh

function elapsed_time() {
    local toMs=1000000
    local start=$1;
    start=$(((start / toMs)));
    local end=$(date +%s%N);
    end=$(((end / toMs)));
    local elapsed=$(((end - start)));
    echo "\e[7;331m ${elapsed}ms \033[0m\t"
}
