#!/usr/bin/env zsh

function emoji_random() {
    local SELECTED_EMOJIS=(
        💩
        🐦
        🚀
        🐞
        🎨
        🍕
        🐭
        👽
        ☕️
        🔬
        💀
        🐷
        🐼
        🐶
        🐸
        🐧
        🐳
        🍔
        🍣
        🍻
        🔮
        💰
        💎
        💾
        💜
        🍪
        🌞
        🌍
        🐌
        🐓
        🍄
    )

    local index=$(($RANDOM%${#SELECTED_EMOJIS[@]}+1))

    echo -n ${SELECTED_EMOJIS[$index]}
}
