#!/usr/bin/env zsh

function google_drive_sync() {
    echo -e "running google drive worker..."
    notify-send "google drive worker" "running..."

    echo -e "syncing local..."
    rsync -au --delete "$HOME/sync/linux/" "$HOME/google-drive/ubuntu/"

    echo -e "removing vendor paths..."
    find "$HOME/google-drive/ubuntu/" -name 'node_modules' \
        -exec /bin/rm rm -rf {} \; 2>/dev/null

    echo -e "syncing virtual..."
    rclone sync --copy-links --check-first --delete-before --delete-excluded --fast-list \
        --progress --rc --rc-enable-metrics --transfers 12 \
        "$HOME/google-drive/ubuntu/" ubuntu:

    echo -e "finish google drive worker"
    notify-send "google drive worker" "finish"
}
