#!/usr/bin/env zsh

function iterate_and_load() {
    local msg="$1"
    log start "$msg"

    local find_path="$2"
    local find_term="$3"
    local filter_fn="$4"

    log debug "find_path=${find_path} • find_term=${find_term} • filter_fn=${filter_fn}"

    eval find "${find_path}" -name "${find_term}" -print 2>/dev/null | \
        "${filter_fn}" | \
        while read -r script_file; do
        log debug "loading $script_file"
        # shellcheck source=/dev/null
        . "$script_file"
    done

    log finish "$msg"
}
