#!/usr/bin/env zsh

function log() {
    level=$1

    silenced_levels=("debug" "start" "finish")

    if ! $SHELL_DEBUG; then
        if [[ ${silenced_levels[@]} =~ $level ]]; then
            return
        fi
    fi

    shift

    . "${DOTFILES}/zsh/functions/caller"

    eval "log_$level '$@'"
}
