#!/usr/bin/env zsh

function log_is_command_success() {
    if [ $? -eq 0 ]; then
        # echo "${CLR_BG_GREEN} 😉 ✔️ ${NO_COLOR}"
        echo "${CLR_BG_GREEN}➿ 😉${NO_COLOR}"
    else
        # echo "${CLR_BG_RED} 🤬 ❌ ${NO_COLOR}"
        echo "${CLR_BG_RED}➿ 🤬${NO_COLOR}"
    fi
}
