#!/usr/bin/env zsh

function sudo() {
	# https://tldp.org/LDP/Bash-Beginners-Guide/html/sect_12_02.html


	# shellcheck disable=SC2312
	if [ "$(id -u)" -eq 0 ]; then
		echo "Hi $USER"
		"$@"
	else
		if ! env sudo --non-interactive true 2>/dev/null; then
			log warn "root privileges are being requested. pay attention to what you are doing!"
			env sudo --validate
		fi
		env sudo "$@"
	fi
}
