#!/usr/bin/env zsh

function vpn_add_route() {
    local host=$1
    local ips=($(vpn_get_ips $host))
    local local_vpn_ip=${2:=$(vpn_ip)}

    vpn_get_ips $host | while read -r ip; do
        vpn_ip_route_add "$ip" "$local_vpn_ip"
    done
}
