#!/usr/bin/env zsh

function zsh_plugins_load() {
    log start "zsh_plugins_load()"

    plugins_path="${ZSH_CUSTOM}/plugins"

    find "$plugins_path" -mindepth 3 -maxdepth 3 -name "*.plugin.zsh" | while read -r item; do
        log_debug $item
        . "$item"
    done
}
