#!/usr/bin/env zsh

function zsh_plugins_install() {
    local _zsh_plugins_list=($(zsh_plugins_list))

    [ ! -d "${ZSH_HOME}/plugins" ] && mkdir -p -m u=rwx,go=rx "${ZSH_HOME}/plugins"

    for p in $_zsh_plugins_list; do
        plugin_path="${ZSH_HOME}/plugins/${p}"

        if [ ! -d "$plugin_path" ]; then
            echo -n "installing zsh plugin ${p}... "
            git clone --quiet "https://github.com/${p}.git" "$plugin_path"
            echo "done"
        fi
    done
}
