#!/usr/bin/env zsh

function zsh_plugins_install() {
    # current_shell_debug=$SHELL_DEBUG
    # SHELL_DEBUG=true

    local _zsh_plugins_list=($(zsh_plugins_list))

    [ ! -d "${ZSH_HOME}/plugins" ] && mkdir -p -m u=rwx,go=rx "${ZSH_HOME}/plugins"

    for p in $_zsh_plugins_list; do
        log_debug "zsh plugin '${p}': "
        plugin_path="${ZSH_HOME}/plugins/${p}"

        if [ ! -d "$plugin_path" ]; then
            log_debug "installing... "
            git clone --quiet "https://github.com/${p}.git" "$plugin_path"
        else
            log_debug "already installed, "
        fi
        log_debug "done"
    done

    # SHELL_DEBUG=$current_shell_debug
}
