#!/usr/bin/env zsh

function ohmyzsh_docker_completions() {
    [ ! -f "$ZSH/plugins/docker/_docker" ] && \
        curl -fLo "$ZSH/plugins/docker/_docker" \
        'https://raw.githubusercontent.com/docker/cli/master/contrib/completion/zsh/_docker'
}
