#!/usr/bin/env zsh

log_starting 'go' 2>/dev/null

command -v go &>/dev/null && echo "go is installed" && exit 0

local version="$(curl -s 'https://go.dev/VERSION?m=text')" # VERSION is UPCASE!

log_info "installing version ${version}" 2>/dev/null

URL="https://golang.org/dl/${version}.linux-amd64.tar.gz"
TMP=$(mktemp -d)
DEST="${TMP}/go.tar.gz"

curl -sL -o "${DEST}" "${URL}"

ls -lah "${DEST}"

sudo rm -rf "${GOROOT}"
sudo tar -C /usr/local -xzf "${DEST}"

export PATH="${PATH}:${GOROOT}/bin"

go version

log_finishing 'go' 2>/dev/null
