services:

  mariadb:

    container_name: mariadb
    env_file:
      - $DOTFILES/mariadb/.env
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: $MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
      MARIADB_AUTO_UPGRADE: $MARIADB_AUTO_UPGRADE
      MARIADB_DATABASE: $MARIADB_DATABASE
      MARIADB_PASSWORD: $MARIADB_PASSWORD
      MARIADB_RANDOM_ROOT_PASSWORD: $MARIADB_RANDOM_ROOT_PASSWORD
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_USER: $MARIADB_USER
      TZ: America/Sao_Paulo
    image: mariadb:lts
    network_mode: bridge
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/data/docker-volumes/mariadb/backup:/backup
      - /mnt/data/docker-volumes/mariadb/data:/var/lib/mysql
      - /sys/fs/cgroup/memory.pressure:/sys/fs/cgroup/memory.pressure
      - $DOTFILES/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf:ro

  adminer:

    image: adminer
    ports:
      - 8306:8306
    restart: always
