#!/usr/bin/env zsh

if [ "$HOSTNAME" = "ubuntu-hyper-v" ]; then
    # shellcheck source=/dev/null
    . "$DOTFILES/dropbox/install"

    # python3 "$HOME/.local/bin/dropbox.py" start -i
    dropbox.py running || dropbox.py start
else
    if [ -f "$HOME/.local/bin/dropbox.py" ]; then
        dropbox.py stop
        frm $HOME/.local/bin/dropbox.py
    fi
    frm $HOME/.dropbox*
fi
