export HOMEBREW_DISPLAY_INSTALL_TIMES=true
export HOMEBREW_UPGRADE_GREEDY=true

alias brew-upgrade='brew update --quiet && brew upgrade --quiet --greedy'

# # brew "bat"
# # brew "chafa"
# # brew "exiftool"
# # brew "fastfetch"
# # brew "fd"
# # brew "ffmpeg"
# # brew "figlet"
# # brew "git-filter-repo"
# # brew "hugo"
# # brew "imagemagick"
# # brew "poppler"
# # brew "ripgrep"
# # brew "tree"
# # brew "fish"
# # brew "fzf"
# # brew "htop"
# # brew "lf"
# # brew "lua"
# # brew "neovim"
# # brew "node"
# # brew "rust"
# # brew "stow"
# # brew "tmux"
# # brew "wget"

# # cask "macvim-app"
# # cask "wezterm"
# brew "bat"
# brew "chafa"
# brew "exiftool"
# brew "fastfetch"
# brew "fd"
# brew "ffmpeg"
# brew "figlet"
# brew "git-filter-repo"
# brew "hugo"
# brew "imagemagick"
# brew "poppler"
# brew "ripgrep"
# brew "tree"
# brew "fish"
# brew "fzf"
# brew "htop"
# brew "lf"
# brew "lua"
# brew "neovim"
# brew "node"
# brew "rust"
# brew "stow"
# brew "tmux"
# brew "wget"
# brew  telnet
# cask "macvim-app"
# cask "wezterm"

# # cask "itsycal"

# # cask "jordanbaird-ice"
# # cask "maccy"
# # cask "stats"

# # cask "bitwarden"
# # cask "skim"

# # cask "firefox"
# # cask "docker-desktop"
# # cask "intellij-idea"
# # cask "kitty"
# # cask "mactex-no-gui"
# # cask "neovide-app"
# # cask "rstudio"
# # cask "utm"

# # cask "discord"
# # cask "minecraft"
# # cask "spotify"

# # cask "notion"

# # cask "cryptomator"
# # cask "filen"
# # cask "nextcloud"
# # cask "syncthing-app"

# # cask "cemu"
# # cask "gimp"
# # cask "keycastr"
# # cask "obs"
# # cask "vlc"

# # cask "tailscale-app"
# # cask "thunderbird"
# # cask "ungoogled-chromium"

# # brew bundle --file ${DOT_DIR}/homebrew/Brewfile_optional

