- defaults:
    clear:
      recursive: true
    link:
      force: true
      ignore-missing: true
      relink: true
    shell:
      stderr: true

- clean: ['~']

- shell:
    - find ~ -xtype l -delete

- link:
    ~/sync: ~/Dropbox/config-backup

- link:
    ~/.config/:
      exclude: [.config/Code]
      glob: true
      path: .config/*
    ~/.config/Code/User/:
      create: true
      glob: true
      path: .config/Code/User/*
    ~/.config/rclone: ~/sync/.config/rclone
    ~/.curecoin: ~/sync/.curecoin
    ~/.epsonscan2: ~/sync/.epsonscan2
    ~/.ethereum: ~/sync/.ethereum
    ~/.gitconfig: .gitconfig
    ~/.icons: ~/sync/.icons
    ~/.inputrc: .inputrc
    ~/.local/share/fonts: ~/sync/.local/share/fonts
    ~/.musicoin: ~/sync/.musicoin
    ~/.pypirc: ~/sync/.pypirc
    ~/.screenrc: .screenrc
    ~/.themes: ~/sync/.themes
    ~/.wakatime.cfg: ~/sync/.wakatime.cfg

- shell:
    - [
        cp --update --remove-destination --backup ~/sync/.gcalcli/oauth ~/.gcalcli_oauth,
        Copying google calendar cli config file,
      ]
    - [fc-cache -f, Updating font cache]
    - [
        gnome-extensions disable auto-move-windows@gnome-shell-extensions.gcampax.github.com 2>/dev/null || true,
        disabling unused ubuntu extensions,
      ]
    - [
        gnome-extensions disable ding@rastersoft.com 2>/dev/null || true,
        disabling unused ubuntu extensions,
      ]
    - [
        gnome-extensions disable ubuntu-dock@ubuntu.com 2>/dev/null || true,
        disabling unused ubuntu extensions,
      ]
    - [
        gnome-extensions disable window-list@gnome-shell-extensions.gcampax.github.com 2>/dev/null || true,
        disabling unused ubuntu extensions,
      ]
    - [
        gnome-extensions disable windowsNavigator@gnome-shell-extensions.gcampax.github.com 2>/dev/null || true,
        disabling unused ubuntu extensions,
      ]
    - [
        gnome-extensions disable workspace-indicator@gnome-shell-extensions.gcampax.github.com 2>/dev/null || true,
        disabling unused ubuntu extensions,
      ]
    - [
        gsettings set org.cinnamon.desktop.wm.preferences num-workspaces 1 2>/dev/null || true,
        disabling workspaces,
      ]
    - [
        gsettings set org.gnome.shell enable-hot-corners true 2>/dev/null || true,
        disabling hot corner,
      ]
    - [
        gsettings set org.gnome.shell.extensions.dash-to-dock autohide false 2>/dev/null || true,
        disabling dock,
      ]
    - [
        gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false 2>/dev/null || true,
        disabling dock,
      ]
    - [
        gsettings set org.gnome.shell.extensions.dash-to-dock intellihide false 2>/dev/null || true,
        disabling dock,
      ]
