services:

  nodejs:

    build:
      context: $DOTFILES/nodejs
      dockerfile: $DOTFILES/nodejs/Dockerfile
      args:
        - UID=$UID

    command: ash
    container_name: nodejs
    env_file:
      - $DOTFILES/nodejs/.env
    environment:
      TZ: America/Sao_Paulo
    image: bernardolm/nodejs:latest
    stdin_open: true
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/data/docker-volumes/nodejs:/home/node
      - ${PWD}:/home/node/app
