#!/usr/bin/env zsh

log info "installing dropbox.py"

[ ! -f ~/.local/bin/dropbox.py ] && \
    curl -sL 'https://www.dropbox.com/download?dl=packages/dropbox.py' \
        -o ~/.local/bin/dropbox.py && \
    chmod u+x ~/.local/bin/dropbox.py && \
    echo " ✔️"
