#!/usr/bin/env zsh

log info "installing revolver"

[ ! -f ~/.local/bin/revolver ] && \
    curl -sL 'https://raw.githubusercontent.com/molovo/revolver/master/revolver' \
        -o ~/.local/bin/revolver && \
    chmod u+x ~/.local/bin/revolver && \
    echo " ✔️"
