#!/usr/bin/env zsh

local __app_name=wakatime-zsh-plugin

log info "installing ${__app_name}"

local __tmp_path="${ZSH_CUSTOM:-$ZSH/custom}/plugins/$__app_name"

[ ! -d "${__tmp_path}" ] \
    && git clone --quiet \
        https://github.com/sobolevn/wakatime-zsh-plugin.git \
        "${__tmp_path}" \
    && echo "✔️"
