#!/usr/bin/env zsh

local __package=zcolors
local __tmp_path="${ZSH_CUSTOM:-$ZSH/custom}/plugins/${__package}"

[ ! -d "${__tmp_path}" ] && SHELL_DEBUG=true log info "installing ${__package}" \
    && git clone --quiet https://github.com/marlonrichert/zcolors.git "${__tmp_path}" \
    && autoload -Uz "${__tmp_path}/functions/zcolors" \
    && zcolors >| ~/.zcolors \
    && source ~/.zcolors \
    && echo "${__package} ✔️"
