#!/usr/bin/env zsh

log info "installing zsh-autosuggestions"

local __tmp_path="${ZSH_CUSTOM:-$ZSH/custom}/plugins/zsh-autosuggestions"

[ ! -d "${__tmp_path}" ] \
    && git clone --quiet \
        https://github.com/zsh-users/zsh-autosuggestions.git \
        "${__tmp_path}" \
    && echo "✔️"
