#!/usr/bin/env zsh

local __package=zsh-autosuggestions
local __tmp_path="${ZSH_CUSTOM:-$ZSH/custom}/plugins/${__package}"

[ ! -d "${__tmp_path}" ] && SHELL_DEBUG=true log info "installing ${__package}" \
    && git clone --quiet \
        https://github.com/zsh-users/zsh-autosuggestions.git \
        "${__tmp_path}" \
    && echo "${__package} ✔️"
