#!/usr/bin/env zsh

docker run \
    --name portainer \
    --restart always \
    -d \
    -p 8000:8000 \
    -p 9000:9000 \
    -p 9443:9443 \
    -v "$HOME/sync/linux/portainer:/data" \
    -v /var/run/docker.sock:/var/run/docker.sock \
    portainer/portainer-ce:latest
