#!/usr/bin/env bash

log start "setup apt packages"

sudo apt-get install --no-install-recommends \
	$(cat ${DOTFILES}/apt/cli.yaml | grep -v '\s+#' | yq '.add.[]' | tr '\n' ' ' | tr '"' ' ')

sudo apt-get purge \
	$(cat ${DOTFILES}/apt/cli.yaml | grep -v '\s+#' | yq '.remove.[]' | tr '\n' ' ' | tr '"' ' ')

# shellcheck source=/dev/null
. "${DOTFILES}/apt/setup-sources"

sudo apt-get install --no-install-recommends \
	$(cat ${DOTFILES}/apt/cli.yaml | grep -v '\s+#' | yq '.3rd-party.[]' | tr '\n' ' ' | tr '"' ' ')

sudo apt-get autoremove --purge

log finish "setup apt packages"
