#!/usr/bin/env bash

log start "pre setup apt"

# sudo apt-get update                                 # NOTE: bypassing temp
# sudo apt-get upgrade --yes --no-install-recommends  # NOTE: bypassing temp

command -v yq >/dev/null || sudo apt install yq

log finish "pre setup apt"
