#!/usr/bin/env bash

# shellcheck source=/dev/null
# . "${DOTFILES}/zsh/functions/log"

log start "pre setup apt"

# sudo apt-get update # NOTE: bypassing temp
# sudo apt-get --yes upgrade # NOTE: bypassing temp

which git &>/dev/null || sudo apt-get --yes install git

log finish "pre setup apt"
