#!/usr/bin/env bash

# shellcheck source=/dev/null
# . "${DOTFILES}/zsh/functions/log"

log info 'setting apt sources'

# function apt_sources_count_list_files() {
#     find /etc/apt/sources.list.d/ -name '*.list' 2>/dev/null | wc -l || 0
# }

# sources_list_bkp_path="/etc/apt/sources.list.d-${TIMESTAMP}"

# log debug "$(apt_sources_count_list_files) source file(s) found"

# if [ "$(apt_sources_count_list_files)" == "0" ]; then
#     log debug 'linking to my own source files'

#     # check if is a link before
#     if [ -d "/etc/apt/sources.list.d" ] || [ -L "/etc/apt/sources.list.d" ]; then
#         log warn 'sources list path not exist or is a sym link. backup it.'
#         sudo mv /etc/apt/sources.list.d "${sources_list_bkp_path}"
#     fi

#     log debug "$(apt_sources_count_list_files) sources file found"

#     sudo ln -sf "${SYNC_DOTFILES}/etc/apt/sources.list.d" /etc/apt/sources.list.d
# fi

# shellcheck source=/dev/null
source "${DOTFILES}/zsh/functions/apt_keys_recovery"; apt_keys_recovery

sudo apt-get update
