function fix_resolvconf() {
    if [[ $(cat /etc/resolv.conf | grep -c 'Generated by NetworkManager' | bc) -eq 1 ]]; then
        echo "generated by network manager, running resolvconf update"
        sudo resolvconf -u
        return
    fi
    echo 'resolvconf is OK, nothind do do...'
}
