#!/usr/bin/env zsh

command -v zsh >/dev/null || (echo 'you needs to install zsh before' && return)

# find ~ -maxdepth 1 -name "*.bkp" -delete
find ~ -name '.zcompdump*' -delete

local files=('.zlogin' '.zlogout' '.zprofile' '.zshenv' '.zshrc')
for f in $files; do
    dest_path="${HOME}/${f}"
    # [ -e "$dest_path" ] && mv "$dest_path" "${dest_path}_${TIMESTAMP}.bkp"
    ln -sf "${DOTFILES}/zsh/startup/${f}" "$dest_path"
done

zsh_plugins_install
