function resolvconf_reset() {
    local resolv_conf="`cat $SYNC_PATH/etc/resolv.conf`"
    sudo cp $SYNC_PATH/etc/resolv.conf /etc/resolv.conf
    docker exec -it ns0 sh -c "echo \"$resolv_conf\" > /etc/resolv.conf"
}

function resolvconf_fix() {
    if [[ $(cat /etc/resolv.conf | grep -c 'Generated by NetworkManager' | bc) -eq 1 ]]; then
        echo "generated by network manager, running resolvconf update"
        sudo resolvconf -u
        return
    fi
    echo 'resolvconf is OK, nothind do do...'
}
