#!/usr/bin/env zsh

log start "linux setup"

log info "calling dotbot to create sym links and others"

CONFIG="${DOTFILES}/linux/links.yaml" \
    DOTBOT_DIR="git/submodules/dotbot" \
    "${DOTFILES}/install" --exit-on-failure

for f in "${DOTFILES}/linux/install.d/*"; do
    [[ -f $f ]] && source -- "$f"
done

log finish "linux setup"
