#!/usr/bin/env /bin/zsh

# log start "pre install linux" # don't work at this point

sudo locale-gen en en_US en_US.UTF-8  # uncomment to commit
sudo update-locale LANG=en_US  # uncomment to commit

# log finish "pre install linux" # don't work at this point
