#!/usr/bin/env /bin/zsh

echo "> linux start"

PATH+=":/snap/bin"
export PATH

export HOSTNAME ; HOSTNAME=$(hostname)
export IP_CURRENT ; IP_CURRENT=$(hostname -I | awk '{print $1}')

alias cat='batcat --number --force-colorization'

echo "> linux finish"
