services:

  postgres:

    container_name: postgres
    env_file:
      - $DOTFILES/postgres/.env
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      TZ: America/Sao_Paulo
    image: postgres:16-alpine
    network_mode: bridge
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/data/docker-volumes/postgres/data:/var/lib/postgresql/data
