services:

  influxdb:

    container_name: influxdb
    env_file:
      - $DOTFILES/influxdb/.env
    environment:
      TZ: America/Sao_Paulo
    image: influxdb:1.8-alpine
    network_mode: bridge
    ports:
      - 8086:8086
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/data/docker-volumes/influxdb:/var/lib/influxdb
      - $DOTFILES/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
