#!/usr/bin/env zsh

function apt_server_pristine() {
    sudo apt purge --yes \
        '*desktop*' \
        '*extra*' \
        '*fonts-tibetan*' \
        '*gnome*' \
        '*gtk*' \
        '*icon*' \
        '*mate*' \
        '*office*' \
        '*theme*' \
        '*x-server*' \
        '*x11*' \
        '*X11*' \
        '*xorg*' \
        '*xserver*'
    sudo apt autoremove --purge --yes
    sudo apt install --yes ubuntu-server ubuntu-server-minimal
}
