#!/usr/bin/env zsh

function audio_reset() {
    sudo killall pulseaudio
    /bin/rm -rf $HOME/.config/pulse/*
    /bin/rm -rf $HOME/.pulse*
    pulseaudio --dump-conf --dump-modules --dump-resample-methods --cleanup-shm --start -D
}
