#!/usr/bin/env zsh

function snap_clean() {
    snap list --all | awk '/disabled/{print $1, $3}' | \
        while read snapname revision; do \
            sudo snap remove "$snapname" --revision="$revision" ; \
        done
}
