- defaults:
    link:
        force: true
        glob: true
        relink: true
    clear:
        recursive: true

- clean: ["~"]

- link:
    ~/.config/:
        glob: true
        path: .config/*
        relink: true
        exclude: [.config/Code]
    ~/.config/Code/User/:
        create: true
        glob: true
        path: .config/Code/User/*
        relink: true
    /etc/apt/sources.list.d: $SYNC_PATH/etc/apt/sources.list.d
    ~/.config/rclone: $SYNC_PATH/.config/rclone
    ~/.curecoin: $SYNC_PATH/.curecoin
    ~/.epsonscan2: $SYNC_PATH/.epsonscan2
    ~/.ethereum: $SYNC_PATH/.ethereum
    ~/.gcalclirc: $SYNC_PATH/.gcalclirc
    ~/.gitconfig: .gitconfig
    ~/.icons: $SYNC_PATH/.icons
    ~/.inputrc: .inputrc
    ~/.local/share/: $SYNC_PATH/.local/share/*
    ~/.local/share/applications: $SYNC_PATH/.local/share/applications
    ~/.local/share/fonts: $SYNC_PATH/.local/share/fonts
    ~/.local/share/gnome-shell: $SYNC_PATH/.local/share/gnome-shell
    ~/.musicoin: $SYNC_PATH/.musicoin
    ~/.pypirc: $SYNC_PATH/.pypirc
    ~/.screenrc: .screenrc
    ~/.themes: $SYNC_PATH/.themes
    ~/.wakatime.cfg: $SYNC_PATH/.wakatime.cfg
    ~/.zshrc: .zshrc
    ~/env.sh: zsh/init/30_env.zsh
    ~/Pictures/Wallpapers: $SYNC_PATH/Pictures/Wallpapers
    ~/ProgramasRFB: $SYNC_PATH/ProgramasRFB
    ~/Sync: ~/Dropbox

- shell:
    - [echo "fs.file-max=131072" | sudo tee -a /etc/sysctl.conf]
    - [echo "vm.max_map_count=524288" | sudo tee -a /etc/sysctl.conf]
    - [echo "vm.swappiness=25" | sudo tee -a /etc/sysctl.conf]
    - [fc-cache -f -v, Updating font cache]
    - [gconftool-2 --shutdown]
    - [gconftool-2 --spawn]
    - [gnome-extensions disable ubuntu-dock@ubuntu.com, Disabling ubuntu dock]
    - [gsettings set org.cinnamon.desktop.wm.preferences num-workspaces 1, Disabling workspaces]
    - [sudo chsh -s $(which zsh), Making zsh the default shell]
    - [sudo dpkg --add-architecture i386]
    - [sudo ulimit -n 131072 || true]
    - [sudo ulimit -u 8192 || true]
