- defaults:
    link:
        force: true
        glob: true
        relink: true
    clear:
        recursive: true

- clean: ["~"]

- link:
    ~/.config/:
        glob: true
        path: .config/*
        relink: true
        exclude: [.config/Code]
    ~/.config/Code/User/:
        create: true
        glob: true
        path: .config/Code/User/*
        relink: true
    ~/.config/rclone: $SYNC_PATH/.config/rclone
    ~/.curecoin: $SYNC_PATH/.curecoin
    ~/.epsonscan2: $SYNC_PATH/.epsonscan2
    ~/.ethereum: $SYNC_PATH/.ethereum
    ~/.gcalclirc: $SYNC_PATH/.gcalclirc
    ~/.gitconfig: .gitconfig
    ~/.icons: $SYNC_PATH/.icons
    ~/.inputrc: .inputrc
    ~/.local/share/: $SYNC_PATH/.local/share/*
    ~/.musicoin: $SYNC_PATH/.musicoin
    ~/.pypirc: $SYNC_PATH/.pypirc
    ~/.screenrc: .screenrc
    ~/.themes: $SYNC_PATH/.themes
    ~/.wakatime.cfg: $SYNC_PATH/.wakatime.cfg
    ~/.zshrc: .zshrc
    ~/env.sh: zsh/init/30_env.zsh
    ~/Pictures/Wallpapers: $SYNC_PATH/Pictures/Wallpapers
    ~/ProgramasRFB: $SYNC_PATH/ProgramasRFB
    ~/Sync: ~/Dropbox

- shell:
    - [fc-cache -f, Updating font cache]
    - [gconftool-2 --shutdown]
    - [gconftool-2 --spawn]
    - [gnome-extensions disable auto-move-windows@gnome-shell-extensions.gcampax.github.com, disabling unused ubuntu extensions]
    - [gnome-extensions disable ding@rastersoft.com, disabling unused ubuntu extensions]
    - [gnome-extensions disable ubuntu-dock@ubuntu.com, disabling unused ubuntu extensions]
    - [gnome-extensions disable window-list@gnome-shell-extensions.gcampax.github.com, disabling unused ubuntu extensions]
    - [gnome-extensions disable windowsNavigator@gnome-shell-extensions.gcampax.github.com, disabling unused ubuntu extensions]
    - [gnome-extensions disable workspace-indicator@gnome-shell-extensions.gcampax.github.com, disabling unused ubuntu extensions]
    - [gsettings set org.cinnamon.desktop.wm.preferences num-workspaces 1, disabling workspaces]
    - [gsettings set org.gnome.shell enable-hot-corners true, disabling hot corner]
    - [gsettings set org.gnome.shell.extensions.dash-to-dock autohide false, disabling dock]
    - [gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false, disabling dock]
    - [gsettings set org.gnome.shell.extensions.dash-to-dock intellihide false, disabling dock]
