- defaults:
    clear:
        recursive: true
    link:
        force: true
        ignore-missing: true
        relink: true
    shell:
        stderr: true

- clean: ["~"]

- shell:
    - find ~ -xtype l -delete

- link:
    ~/sync: ~/Dropbox/config-backup

- link:
    ~/.config/:
        exclude: [.config/Code]
        glob: true
        path: .config/*
    ~/.config/Code/User/:
        create: true
        glob: true
        path: .config/Code/User/*
    ~/.local/share:
        glob: true
        path: ~/sync/.local/share/*
    ~/.config/rclone: ~/sync/.config/rclone
    ~/.curecoin: ~/sync/.curecoin
    ~/.epsonscan2: ~/sync/.epsonscan2
    ~/.ethereum: ~/sync/.ethereum
    ~/.gcalcli_oauth: ~/sync/.gcalcli_oauth
    ~/.gcalclirc: ~/sync/.gcalclirc
    ~/.gitconfig: .gitconfig
    ~/.icons: ~/sync/.icons
    ~/.inputrc: .inputrc
    ~/.local/share/fonts: ~/sync/.local/share/fonts
    ~/.musicoin: ~/sync/.musicoin
    ~/.pypirc: ~/sync/.pypirc
    ~/.screenrc: .screenrc
    ~/.themes: ~/sync/.themes
    ~/.wakatime.cfg: ~/sync/.wakatime.cfg
    ~/.zshrc: .zshrc
    ~/env.sh: zsh/init/30_env.zsh
    ~/Pictures/Wallpapers: ~/sync/Pictures/Wallpapers
    ~/ProgramasRFB: ~/sync/ProgramasRFB

- shell:
    - gconftool-2 --shutdown
    - gconftool-2 --spawn
    - [fc-cache -f,
        Updating font cache]
    - [gnome-extensions disable auto-move-windows@gnome-shell-extensions.gcampax.github.com,
        disabling unused ubuntu extensions]
    - [gnome-extensions disable ding@rastersoft.com,
        disabling unused ubuntu extensions]
    - [gnome-extensions disable ubuntu-dock@ubuntu.com,
        disabling unused ubuntu extensions]
    - [gnome-extensions disable window-list@gnome-shell-extensions.gcampax.github.com,
        disabling unused ubuntu extensions]
    - [gnome-extensions disable windowsNavigator@gnome-shell-extensions.gcampax.github.com,
        disabling unused ubuntu extensions]
    - [gnome-extensions disable workspace-indicator@gnome-shell-extensions.gcampax.github.com,
        disabling unused ubuntu extensions]
    - [gsettings set org.cinnamon.desktop.wm.preferences num-workspaces 1,
        disabling workspaces]
    - [gsettings set org.gnome.shell enable-hot-corners true,
        disabling hot corner]
    - [gsettings set org.gnome.shell.extensions.dash-to-dock autohide false,
        disabling dock]
    - [gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false,
        disabling dock]
    - [gsettings set org.gnome.shell.extensions.dash-to-dock intellihide false,
        disabling dock]
