alias ack='ag && ag || ack'
alias brew-upgrade='brew update --quiet && brew upgrade --quiet --greedy'
alias dc='docker ps -a --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"'
alias di='docker images -a'
alias frm='/bin/rm -rf'
alias gb='git branch'
alias gbd='git branch -D'
alias gbr='git branch --remote'
alias gc='git commit --verbose -S'
alias gco='git checkout'
alias gfp='git fetch --all --prune'
alias ggpull='git pull origin'
alias ggpush='git push origin'
alias ggsync='gfp ; git stash ; ggpull ; ggpush ; git stash pop'
alias gsl='git stash list'
alias gssh='gcloud compute ssh --tunnel-through-iap'
alias gst='git status --branch --show-stash --untracked-files=all --ignore-submodules=untracked --column=always --renames --find-renames=70%'
alias la='eza -lah --icons --color=auto --group-directories-first'
alias new-guid='uuidgen | tr "[A-Z]" "[a-z]"'
alias ovpn-conn-log='tail -f $HOME/Library/Application\ Support/OpenVPN\ Connect/log/ovpn.log'
alias path='echo -e ${PATH//:/\\n}'
alias ports='sudo lsof -i -P -n | grep LISTEN'
alias s='screen'
alias sl='screen -list'
alias sr='screen -r'
alias tf='reset ; terraform'
